# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: automatic-parakeet-bluebuild
description: Custom Aurora-DX with bluebuild (b43 wifi)

base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable

modules:
  - type: dnf
    install:
      packages:
        - webkit2gtk4.1

  - type: bling
    install:
      - rpmfusion

  # Enable RPM Fusion "nonfree tainted" repo (needed for b43-firmware)
  - type: rpm-ostree
    install:
      - rpmfusion-nonfree-release-tainted

  # Install Broadcom b43 firmware (kernel module b43 is already in the kernel; firmware is the missing piece)
  - type: rpm-ostree
    install:
      - b43-firmware

  - type: signing

