# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: automatic-parakeet-bluebuild
description: Custom Aurora-DX with bluebuild

base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable

modules:
  - type: dnf
    install:
      packages:
        - webkit2gtk4.1

  - type: bling
    install:
      - rpmfusion

  - type: akmods
    install:
      - wl

  - type: rpm-ostree
    install:
      - broadcom-wl

  - type: files
    files:
      - source: etc/modules-load.d/wl.conf
        destination: /etc/modules-load.d/wl.conf

  - type: signing

