---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: automatic-parakeet-bluebuild
description: Custom Aurora-DX with bluebuild

base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable

modules:
  - type: dnf
    install:
      packages:
        - webkit2gtk4.1

  # Pull prebuilt Broadcom wl kernel module from ublue akmods
  - type: akmods
    base: main        # matches Aurora’s kernel family
    install:
      - wl

  # Ensure wl is requested at boot
  - type: files
    files:
      - path: etc/modules-load.d/wl.conf
        content: |
          wl

  - type: signing

